name: vanacue_mobile
description: "A new Flutter project for Vanacue Streaming."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.0
  screenshot: ^2.5.0
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  image_gallery_saver_plus: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vnce_app_icon.png"
  adaptive_icon_background: "#4A0000"
  adaptive_icon_foreground: "assets/images/vnce_4_launcher.png"

flutter_native_splash:
  color: "#4A0000"
  image: "assets/images/vnce_4_padded.png"
  android_12:
    color: "#4A0000"
    image: "assets/images/vnce_4_padded.png"
